
library(ggplot2)
library(data.table)
library(dplyr)
library(dplyr)
library(reshape)
library(pheatmap)
library(maftools)
library(stringr)

common_params <- c("SAMPLE_NAME","ANOMALY_QC_FILTER","ANOMALY_QC_FILTER_TEST_1","VARIATIONS_QC_FILTER","VARIATIONS_QC_FILTER_TEST_1","UNIQUE_FRAGMENT_TOTAL","UNIQUE_FRAGMENT_ALIGNED","UNIQUE_FRAGMENT_FILTERED","UNIQUE_FRAGMENT_FILTERED_ON_TARGET","UNIQUE_FRAGMENT_FILTERED_ON_TARGET_PERCENT","UNIQUE_FRAGMENT_FILTERED_OFF_TARGET","UNIQUE_FRAGMENT_FILTERED_OFF_TARGET_PERCENT","RAW_FRAGMENT_TOTAL","RAW_FRAGMENT_ALIGNED","RAW_FRAGMENT_FILTERED","RAW_FRAGMENT_FILTERED_ON_TARGET","RAW_FRAGMENT_FILTERED_ON_TARGET_PERCENT","RAW_FRAGMENT_FILTERED_OFF_TARGET","RAW_FRAGMENT_FILTERED_OFF_TARGET_PERCENT","JUNK_PERCENT","ON_TARGET_DEDUPLICATION_RATIO","TOTAL_UNIQUE_RNA_START_SITES","TOTAL_UNIQUE_RNA_START_SITES_PERCENT","TOTAL_UNIQUE_DNA_START_SITES","TOTAL_UNIQUE_DNA_START_SITES_PERCENT","TOTAL_UNIQUE_AMBIG_START_SITES","TOTAL_UNIQUE_AMBIG_START_SITES_PERCENT","TOTAL_UNIQUE_DNA_AND_AMBIG_START_SITES","TOTAL_UNIQUE_DNA_AND_AMBIG_START_SITES_PERCENT","TOTAL_UNIQUE_START_SITES","AVERAGE_UNIQUE_RNA_READS_PER_GSP2","AVERAGE_UNIQUE_RNA_READS_PER_CONTROL_GSP2","AVERAGE_UNIQUE_DNA_READS_PER_GSP2","AVERAGE_UNIQUE_DNA_READS_PER_CONTROL_GSP2","AVERAGE_UNIQUE_AMBIG_READS_PER_GSP2","AVERAGE_UNIQUE_AMBIG_READS_PER_CONTROL_GSP2","AVERAGE_UNIQUE_DNA_AND_AMBIG_READS_PER_GSP2","AVERAGE_UNIQUE_DNA_AND_AMBIG_READS_PER_CONTROL_GSP2","AVERAGE_RAW_RNA_READS_PER_GSP2","AVERAGE_RAW_RNA_READS_PER_CONTROL_GSP2","AVERAGE_RAW_DNA_READS_PER_GSP2","AVERAGE_RAW_DNA_READS_PER_CONTROL_GSP2","AVERAGE_RAW_AMBIG_READS_PER_GSP2","AVERAGE_RAW_AMBIG_READS_PER_CONTROL_GSP2","AVERAGE_RAW_DNA_AND_AMBIG_READS_PER_GSP2","AVERAGE_RAW_DNA_AND_AMBIG_READS_PER_CONTROL_GSP2","AVERAGE_UNIQUE_RNA_START_SITES_PER_GSP2","AVERAGE_UNIQUE_RNA_START_SITES_PER_CONTROL_GSP2","AVERAGE_UNIQUE_DNA_START_SITES_PER_GSP2","AVERAGE_UNIQUE_DNA_START_SITES_PER_CONTROL_GSP2","AVERAGE_UNIQUE_AMBIG_START_SITES_PER_GSP2","AVERAGE_UNIQUE_AMBIG_START_SITES_PER_CONTROL_GSP2","AVERAGE_UNIQUE_DNA_AND_AMBIG_START_SITES_PER_GSP2","AVERAGE_UNIQUE_DNA_AND_AMBIG_START_SITES_PER_CONTROL_GSP2","AVERAGE_UNIQUE_START_SITES_PER_GSP2","UNIQUE_FRAGMENT_MEAN_LENGTH","UNIQUE_FRAGMENT_MEDIAN_LENGTH","UNIQUE_RNA_FRAGMENT_MEAN_LENGTH","UNIQUE_RNA_FRAGMENT_MEDIAN_LENGTH","UNIQUE_DNA_FRAGMENT_MEAN_LENGTH","UNIQUE_DNA_FRAGMENT_MEDIAN_LENGTH","UNIQUE_AMBIG_FRAGMENT_MEAN_LENGTH","UNIQUE_AMBIG_FRAGMENT_MEDIAN_LENGTH","TOTAL_UNIQUE_RNA_READS","TOTAL_UNIQUE_RNA_READS_PERCENT","TOTAL_UNIQUE_DNA_READS","TOTAL_UNIQUE_DNA_READS_PERCENT","TOTAL_UNIQUE_AMBIG_READS","TOTAL_UNIQUE_AMBIG_READS_PERCENT","TOTAL_UNIQUE_DNA_AND_AMBIG_READS","TOTAL_UNIQUE_DNA_AND_AMBIG_READS_PERCENT","TOTAL_RAW_RNA_READS","TOTAL_RAW_RNA_READS_PERCENT","TOTAL_RAW_DNA_READS","TOTAL_RAW_DNA_READS_PERCENT","TOTAL_RAW_AMBIG_READS","TOTAL_RAW_AMBIG_READS_PERCENT","TOTAL_RAW_DNA_AND_AMBIG_READS","TOTAL_RAW_DNA_AND_AMBIG_READS_PERCENT","TOTAL_UNIQUE_RNA_CONTROL_READS","TOTAL_UNIQUE_RNA_CONTROL_READS_PERCENT","TOTAL_UNIQUE_DNA_CONTROL_READS","TOTAL_UNIQUE_DNA_CONTROL_READS_PERCENT","TOTAL_UNIQUE_AMBIG_CONTROL_READS","TOTAL_UNIQUE_AMBIG_CONTROL_READS_PERCENT","TOTAL_UNIQUE_DNA_AND_AMBIG_CONTROL_READS","TOTAL_UNIQUE_DNA_AND_AMBIG_CONTROL_READS_PERCENT","TOTAL_RAW_RNA_CONTROL_READS","TOTAL_RAW_RNA_CONTROL_READS_PERCENT","TOTAL_RAW_DNA_CONTROL_READS","TOTAL_RAW_DNA_CONTROL_READS_PERCENT","TOTAL_RAW_AMBIG_CONTROL_READS","TOTAL_RAW_AMBIG_CONTROL_READS_PERCENT","TOTAL_RAW_DNA_AND_AMBIG_CONTROL_READS","TOTAL_RAW_DNA_AND_AMBIG_CONTROL_READS_PERCENT","MOLBAR_TOTAL_NUM_READS","MOLBAR_READS_WITH_CORRECT_COMMON_REGION","MOLBAR_FRACTION_OF_TOTAL","SEQUENCED_READ_COUNT","NORMALIZED_READ_COUNT","FAILED_CYCLE_COUNT","NUM_READS_AFTER_TRIMMING_ADAPTERS")

setwd("/mnt/tchandra-lab/Neil/data/DNA-seq/LBC_ARCHER_Panel-seq/")

manifest <- read.table("ARCHER_PanelSeq_Metadata_SEH_deduped.All.tsv", header = T, sep = "\t", stringsAsFactors = FALSE)
manifest$qc_filenames <- paste("./data/", manifest$Run_Folder, "/", gsub(".fastq.gz", "", manifest$Original_Filename), "_full_results.txt", sep = "")

files <- lapply(manifest$qc_filenames, read.table, sep="\t", header = F, row.names = 1)

transform_meta <- function(file) {
  file <- file[ rownames(file) %in% common_params , ]
  file <- t(file)
  file <- data.table(file)
}
transformed_files <- lapply(files, transform_meta)
data <- rbindlist( transformed_files )
data <- as.data.frame(data)
colnames(data) <- common_params

x <- cbind(manifest, data)
write.table(x, "ARCHER_PanelSeq_Metadata.QC_info.tsv", sep = "\t", row.names = F)
